'''
입양을 보낸 동물 중, 가장 보호 기간이 길었던 두마리의 동물을 출력한다.
'''

SELECT I.ANIMAL_ID, I.NAME
FROM ANIMAL_INS AS I
LEFT JOIN ANIMAL_OUTS AS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE O.DATETIME is NOT Null
ORDER BY (o.DATETIME-i.DATETIME) DESC
LIMIT 2